---
title: "bootstrapping"
author: "Shihui Peng"
date: "2023-12-01"
output: github_document
---
```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(p8105.datasets)
library(modelr)
set.seed(1)
```

# generate a relevant example

```{r}
n_samp = 250

# create a ds w constant variance
sim_df_const =
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

# create a ds w non-constant variance
sim_df_nonconst =
  sim_df_const |> 
  mutate(
    error = error * 0.75 * x,
    y = 2 + 3 * x + error
  )


sim_df = 
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source")

sim_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```

# fit some linear models

```{r}
sim_df_const |> 
  lm(y~x, data = _) |> 
  broom::tidy()

sim_df_nonconst |> 
  lm(y~x, data = _) |> 
  broom::tidy()
```
* but we know that non-constant error ds does not meet linear reg assumptions, so we cannot trust the CI coming out from a linear reg model.
